# Generated by Django 4.2.7 on 2023-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movies_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='ffffff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
